### ISSUE TITLE
CoDyCo superbuild wont install

### ISSUE THREAD

**Issue by MoritzN89** [robotology/codyco-modules#80] opened 2014-11-21 15:02 UTC
Hello,
when I try to do "make" in codyco-superbuild/build I get this errors:

Linking CXX executable ../../../bin/locomotionControl
/usr/lib/libctrlLib.a(minJerkCtrl.cpp.o): In function `iCub::ctrl::minJerkVelCtrlForNonIdealPlant::setPlantParameters(yarp::os::Property const&, std::string const&, yarp::os::Bottle const&)':
minJerkCtrl.cpp:(.text+0xb4c8): undefined reference to `yarp::os::Property::check(yarp::os::ConstString const&)'
minJerkCtrl.cpp:(.text+0xb5cc): undefined reference to `yarp::os::Property::find(yarp::os::ConstString const&)'
collect2: error: ld returned 1 exit status
make[5]: *** [bin/locomotionControl] Error 1
make[4]: *** [src/modules/locomotionControl/CMakeFiles/locomotionControl.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [main/codyco-modules/CMakeFiles/YCMStamp/codyco-modules-build] Error 2
make[1]: *** [CMakeFiles/codyco-modules.dir/all] Error 2
make: *** [all] Error 2

I dont know what to do so I would be glad if someone can help me!
I am using Ubuntu 14.04 64 Bit and Matlab R2013a

**Comment by francesco-romano** [comment] 2015-01-14 10:28
Hi @MoritzN89  (cc @traversaro)
What is the status of this issue?
Have you managed to solve it?

**Comment by MoritzN89** [comment] 2015-01-14 10:47
I managed it to install everything, but the robot stills goes crazy (see https://github.com/robotology-playground/WBI-Toolbox/issues/33). I tried many different gains but the robot falls on the ground or flies around the simulator. When I used the fixed feet icub model he managed it not to fall down or something, but makes strange movements (keeps up the arm and stuff). We explained this our supervisor and he means that we have to limit the torques additionaly. We have tried this but the results were not much better (this must be an fail on the wbi contruction?). So we are very frustrated at time.

**Comment by francesco-romano** [comment] 2015-01-14 10:53
@MoritzN89 Ok.
Because you opened the other issue and this one is solved I close this.
About the other issue I think that as soon as we have a stable gazebo/simulink synchronizer we can narrow the causes of the issue and hopefully solve it.

**Closed by francesco-romano** 2015-01-14 10:53 UTC
