### ISSUE TITLE
[torqueBalancing] Find a good position for the icub attached to the mechanical crane

### ISSUE THREAD

**Issue by traversaro** [robotology/codyco-modules#177] opened 2016-03-19 15:58 UTC
The position should be such that lowering the crane the iCub should be able to be on two feet without any human assistance. 

Technically speaking, such a property can be stated geometrically in the following way. Let's define the "sole plane" as the shared plane of the two soles, and the 
"vertical plane" as the plane defined by there points: the robot COM, and the two points in the shoulder at which the robot is connected to the crane. In the desirable configuration the vertical plane and the sole plane should be perpendicular.

**Comment by traversaro** [comment] 2019-03-15 14:44
This is still a relevant issue I think, what do you think @gabrielenava ? :D

**Comment by gabrielenava** [comment] 2019-03-15 16:04
Guess the issue is slightly outdated. In fact, now the robot does not even need the crane anymore:

![takeoff](https://user-images.githubusercontent.com/12396934/51545558-8516c100-1e62-11e9-9819-86cd2e2e1bc5.gif)

**Comment by gabrielenava** [comment] 2019-03-23 12:02
Closing as outdated issue. Home position for iCub + crane has been already selected and it is now pretty stable.

**Closed by gabrielenava** 2019-03-23 12:02 UTC
Labels: TorqueBalancing
